### ISSUE TITLE
Powerstream Support

### ISSUE THREAD

**Issue by 011gwerc01** [tolwi/hassio-ecoflow-cloud#62] opened 2023-06-21 05:10 UTC
Hi,
I tried the hassio integration with my Delta Max and it's working great. Thank you for working on this topic, as Ecoflow integration into HA is a real pain :)

I couldn't find a way to set the household consumption for Powerstream based on my current energy consumption programmatically. Then i came across your Git project.

Do you have plans to integrate Ecoflow's new Microinverter PowerStream as well?

**Comment by buffcode** [comment] 2023-06-21 19:08
Duplicate of https://github.com/tolwi/hassio-ecoflow-cloud/issues/54

**Comment by 011gwerc01** [comment] 2023-06-21 19:17
Sorry, missed that one :)

Thank you!

**Closed** 2023-06-23 06:15 UTC
