### ISSUE TITLE
Entities are updates only when Ecoflow app is open

### ISSUE THREAD

**Issue by samfromlv** [tolwi/hassio-ecoflow-cloud#57] opened 2023-06-15 05:22 UTC
I am using v0.8.9 with Delta2. No matter what I set in refresh rate in configuration, entities state is not refreshed automatically. Entities are refreshed automatically while I am using Ecoflow android application, otherwise the state stays the same for hours.

Any suggestions how to debug it?

**Comment by Tommi1977** [comment] 2023-06-15 06:16
Same here with River 2 Pro since yesterday

**Comment by buffcode** [comment] 2023-06-16 11:01
Reloading the integration forced an update, but the data won't be updated afterwards. Seems to be device-independent, Delta Pro here.

**Comment by vedranius** [comment] 2023-06-18 15:26
same with my River 2 Max

**Comment by unze** [comment] 2023-06-18 16:57
Same Here. River 2 Pro

**Comment by samfromlv** [comment] 2023-06-18 21:33
I have researched this issue and it seems that the reason is in the Ecoflow API. The workaround for now is to reload integration and do not open the Ecoflow App after this (Settings > Integrations > EcoFlow-Cloud > Three dots > Reload).

I have created a second account, installed Ecoflow to another Android phone and shared my Delta 2 with a newly created account. The issue is reproducible using two phones. Open two Ecoflow apps on different devices, open the device dashboard, observe that metrics are updated on both devices, force close the application on the first device, and now app on the second device will stop receiving the updates. The only way to start getting updates on second device it is to force close the app and restart it.

I have checked integration debug logs, and there are no disconnects nor errors.
I have tried using different IP addresses on two devices, doesn't help.

As mentioned before, reloading integration does help and entities are updated until you open the Ecoflow app, or anyone who can access your device opens the app. I have contacted in-app support to report the issue.

**Comment by faken** [comment] 2023-06-21 16:51
I've resolved this issue with a hass.io automation: 

```
alias: Restart EcoFlow Integration
description: ""
trigger:
  - platform: time_pattern
    minutes: /5
condition: []
action:
  - service: homeassistant.reload_config_entry
    data: {}
    target:
      entity_id: number.test_ac_charging_power
mode: single
```

**Comment by unze** [comment] 2023-06-21 17:01
> 

Thanks, good Idea.
What ist your "entity_id: number.test_ac_charging_power"

**Comment by neotigger** [comment] 2023-06-21 17:14
Genauso mach ich es auch, bei mir läuft die Automation 2x in der Stunde. Lieber ein paar Sekunden keine Daten, als stundenlang die falschen.

**Comment by faken** [comment] 2023-06-21 17:30
> Thanks, good Idea.
> What ist your "entity_id: number.test_ac_charging_power"

My entity is currently just called test.

**Comment by tolwi** [comment] 2023-06-22 16:01
@samfromlv following your original description it looks like ecoflow somehow tracks application activity and updates data only when app is opened. The only periodical message I've found is "setRtcTime" (each 20sec), so I've implemented such 'pinging' for Delta2 in [main_ping_sensor](https://github.com/tolwi/hassio-ecoflow-cloud/tree/main_ping_sensor) branch. In order to activate it - go to device config and set `Ping period` to 20.

**Comment by faken** [comment] 2023-06-23 06:05
@tolwi I've checked your work in the `main_ping_sensor`-branch, but it seems to not have fixed the issue. The values are again not updated after a period of approximately 5 minutes. I am back to restarting the integration.

**Comment by Milchbeck** [comment] 2023-06-29 08:22
> I've resolved this issue with a hass.io automation: 
> 
> 
> 
> ```
> 
> alias: Restart EcoFlow Integration
> 
> description: ""
> 
> trigger:
> 
>   - platform: time_pattern
> 
>     minutes: /5
> 
> condition: []
> 
> action:
> 
>   - service: homeassistant.reload_config_entry
> 
>     data: {}
> 
>     target:
> 
>       entity_id: number.test_ac_charging_power
> 
> mode: single
> 
> ```

How I can make this?

**Comment by unze** [comment] 2023-06-29 19:50
Settings->Automations->Create->in the upper right corner "edit as yaml"

![image](https://github.com/tolwi/hassio-ecoflow-cloud/assets/128616/f71e0de5-e056-4662-95e4-4adffff29b4e)

**Comment by Milchbeck** [comment] 2023-06-29 20:34
> Settings->Automations->Create->in the upper right corner "edit as yaml"
> 
> 
> 
> ![image](https://github.com/tolwi/hassio-ecoflow-cloud/assets/128616/f71e0de5-e056-4662-95e4-4adffff29b4e)
> 
> 
> 
> replace code

Supiii Danke 🤙

**Comment by Milchbeck** [comment] 2023-06-29 20:39
Und was gebe ich bei id number.Test ein?

**Comment by tolwi** [comment] 2023-06-30 18:20
another try for Delta2 and River2Max - [main_status_sensor](https://github.com/tolwi/hassio-ecoflow-cloud/tree/main_status_sensor)

**Comment by Milchbeck** [comment] 2023-06-30 22:39
How I can install this 👆

**Comment by tolwi** [comment] 2023-07-01 07:40
> another try for Delta2 and River2Max - [main_status_sensor](https://github.com/tolwi/hassio-ecoflow-cloud/tree/main_status_sensor)

https://github.com/tolwi/hassio-ecoflow-cloud/releases/tag/v0.10.0-pre

**Comment by Tommi1977** [comment] 2023-07-01 07:48
> I have researched this issue and it seems that the reason is in the Ecoflow API. The workaround for now is to reload integration and do not open the Ecoflow App after this (Settings > Integrations > EcoFlow-Cloud > Three dots > Reload).
> 
> I have created a second account, installed Ecoflow to another Android phone and shared my Delta 2 with a newly created account. The issue is reproducible using two phones. Open two Ecoflow apps on different devices, open the device dashboard, observe that metrics are updated on both devices, force close the application on the first device, and now app on the second device will stop receiving the updates. The only way to start getting updates on second device it is to force close the app and restart it.
> 
> I have checked integration debug logs, and there are no disconnects nor errors. I have tried using different IP addresses on two devices, doesn't help.
> 
> As mentioned before, reloading integration does help and entities are updated until you open the Ecoflow app, or anyone who can access your device opens the app. I have contacted in-app support to report the issue.

I do agree:
I have not opened the Ecoflow-App for the last 2 weeks - and no problems with the HA integration. I control my River 2 pro completely over HA

**Comment by tolwi** [comment] 2023-07-03 10:38
Delta2/River2Max owners - try v0.10.0-pre2.
Long story short - reconnecting mqtt client recovers 'activity' in the data topic.
If this solution resolves the issue for all delat2/river2max owners - I'll try to generify this approach for other devices.

**Comment by Milchbeck** [comment] 2023-07-03 10:56
> Delta2/River2Max owners - try v0.10.0-pre2.
> 
> Long story short - reconnecting mqtt client recovers 'activity' in the data topic.
> 
> If this solution resolves the issue for all delat2/river2max owners - I'll try to generify this approach for other devices.

For now it's working for my Delta 2 Max & River 2 Pro 💪

**Comment by tolwi** [comment] 2023-07-03 11:25
> > Delta2/River2Max owners - try v0.10.0-pre2.
> > Long story short - reconnecting mqtt client recovers 'activity' in the data topic.
> > If this solution resolves the issue for all delat2/river2max owners - I'll try to generify this approach for other devices.
> 
> For now it's working for my Delta 2 Max & River 2 Pro 💪

it is only for Delta2 and River2Max as i can debug only this devices

**Comment by unze** [comment] 2023-07-03 11:43
> > > Delta2/River2Max owners - try v0.10.0-pre2.
> > > Long story short - reconnecting mqtt client recovers 'activity' in the data topic.
> > > If this solution resolves the issue for all delat2/river2max owners - I'll try to generify this approach for other devices.
> > 
> > 
> > For now it's working for my Delta 2 Max & River 2 Pro 💪
> 
> it is only for Delta2 and River2Max as i can debug only this devices

yes, i can confirm it's not working for River 2 Pro, as you wrote it's only for the river 2 max and delta 2

**Comment by Milchbeck** [comment] 2023-07-03 19:04
I don't but for me work's great with my River 2 Pro and Delta2 Max

**Comment by tolwi** [comment] 2023-07-05 18:03
v0.10.0

**Comment by Milchbeck** [comment] 2023-07-05 19:33
Thx 🙏🏼

**Comment by tolwi** [comment] 2023-07-07 06:42
need verification feedback to close the issue - anybody?

**Comment by vedranius** [comment] 2023-07-07 07:07
> need verification feedback to close the issue - anybody?

I'm sorry, but how do I upgrade to that version?

**Comment by Tommi1977** [comment] 2023-07-07 13:07
My River 2 Pro runs without the update - I assume because I have not used the app during the last 3 weeks ;-)
so therefore I'm a little afraid to update from V. 0.8.9 (never change a running system...)

**Comment by unze** [comment] 2023-07-07 19:56
I can confirm its working.
River 2 Pro

**Closed** 2023-07-09 15:43 UTC

**Comment by Milchbeck** [comment] 2023-07-11 21:25
When we see Powerstream???
